# Generated by Django 5.0.2 on 2025-04-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={},
        ),
        migrations.RemoveField(
            model_name='author',
            name='twitter',
        ),
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(default='https://example.com', max_length=250),
        ),
    ]
