# Generated by Django 5.0.2 on 2025-04-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_feed_options_remove_author_twitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.CharField(max_length=250),
        ),
    ]
