# Generated by Django 5.0.2 on 2025-04-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_categoryfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='categoryfeed',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
