# Generated by Django 5.0.2 on 2025-04-07 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_category_link_alter_categoryfeed_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='link',
        ),
    ]
